/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jvlwjgl;

import platformer.PlatformerGame;
import snake.SnakeGame;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // Main Application Loop
        while (true) {
            // Show Main Menu and wait for selection
            MainMenu menu = new MainMenu();
            MainMenu.Selection selection = menu.run();

            // Handle Selection
            if (selection == MainMenu.Selection.EXIT) {
                break;
            } else if (selection == MainMenu.Selection.PLATFORMER) {
                // Run Platformer (blocks until returned)
                new PlatformerGame().run();
            } else if (selection == MainMenu.Selection.SNAKE) {
                // Run Snake (blocks until returned)
                new SnakeGame().run();
            }
            
            // Loop continues, reopening menu unless EXIT
        }
    }
}
